#
# Holographic Displays Placeholder Extension
# This plugin is made by NeutralPlasma/Gasper Lukman
# You can get more support on his discord server or by sending
# private discord message to him
# Discord: Gasper Lukman#5649
# Discord server: https://discord.gg/Zpks2WK
#

config-version: 1

addons: []



