name: HolographicPlaceholders
main: com.neutralplasma.holographicPlaceholders.HolographicPlaceholders
version: @version@
api-version: "1.13"
author: NeutralPlasma

depend: [Vault]

softdepend: [PlaceholderAPI, HolographicDisplays, SimpleHolograms, ProtocolLib]

commands:
  hpe:
    permission: holographicplaceholders.command.main
    usage: /<command>

permissions:
  holographicplaceholders.command.main:
    default: op
    description: Main permission.
  holographicplaceholders.command.reload:
    default: op
    description: Reload permission.
  holographicplaceholders.command.setsign:
    default: op
    description: Set sign permission.
  holographicplaceholders.command.sethead:
    default: op
    description: Set head permission.
  holographicplaceholders.command.removehead:
    default: op
    description: Remove head permission.
  holographicplaceholders.command.removesign:
    default: op
    description: Remove sign permission.
